/**
 * events.js - Waseda Calendar イベントデータ管理ファイル
 *
 * 【運営者向け】
 * このファイルにイベント情報を追加・修正・削除することで
 * サイトのイベント情報が更新されます。
 *
 * 一般ユーザーはこのファイルを変更できません。
 * イベント情報の変更は運営者のみが行ってください。
 *
 * 日付形式: YYYY-MM-DD (例: 2025-06-15)
 * 時間形式: HH:MM (例: 14:00)
 *
 * endDate（任意）:
 *   複数日にわたるイベントの終了日。指定すると、カレンダー上で開始日(date)から
 *   終了日(endDate)まで連続したバーとして表示されます。省略した場合は単日イベントとして扱われます。
 *
 * category の選択肢:
 *   "sports" | "culture" | "music" | "theater" | "lecture" | "community" | "other"
 *
 * scope の選択肢:
 *   "schedule" | "circle"
 *   トップページの大枠フィルタ（全部・学事日程・サークルイベント）で使う分類。
 *   "schedule" → 学事日程（授業期間・休業・式典など、大学が主体の日程）
 *   "circle"   → サークル・団体が主催する個別イベント（掲載依頼経由で追加するものは基本これ）
 *   省略した場合は "circle" として扱われる。
 *
 * weeklyClassOnly（任意・true/省略）:
 *   「春学期○週目」「秋学期○週目」「授業予備週/期間」など、授業が行われる期間そのものを表す
 *   学事日程にのみ true を付ける。true が付いたイベントは、日曜日は授業日ではないため
 *   カレンダー上で日曜日には表示されない（script.js の isHiddenOnSunday を参照）。
 *   オープンキャンパス・早稲田祭・卒業式・休業開始/終了・臨時休業など「授業の有無」とは関係ない
 *   学事日程には付けないこと（土日を含む期間全体をそのまま表示したいため）。
 *
 * target の選択肢:
 *   "student" | "obog" | "public" | "applicant"
 *   ※ 複数選択可（配列で指定）
 *
 * campus の選択肢:
 *   "waseda" | "toyama" | "nishiwaseda" | "tokorozawa" | "takadanobaba" | "outside" | "online"
 *
 * feeType の選択肢:
 *   "free" | "paid"
 *
 * isPublished:
 *   true → サイトに表示する
 *   false → 非表示（下書き）
 *
 * imageUrl（任意）:
 *   検索結果の構造化データ（schema.org/Event）に使う画像URL。未指定の場合はサイト共通のOGP画像が使われる。
 *
 * orgId（任意）:
 *   organizations.js の団体IDと紐づける場合に指定（例: "org-001"）。
 *   指定すると、終了済み（today > endDate）になった際にその団体のプロフィールページの
 *   「開催実績」一覧に表示されるようになる。既存イベントはorganizerのテキストのままでよく、
 *   orgIdは新規イベントから付与していく運用とする。
 *
 * reactions:
 *   現時点では静的な件数表示のみ。未指定の場合はすべて0件として扱われます。
 */

const EVENTS = [

  // ========================================
  // 2026年度 学事日程
  // ========================================

  {
    id: "evt-011",
    title: "春学期授業1週目",
    date: "2026-04-11",
    endDate: "2026-04-17",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "春学期の授業期間（1週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-012",
    title: "春学期授業2週目",
    date: "2026-04-18",
    endDate: "2026-04-24",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "春学期の授業期間（2週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-013",
    title: "春学期授業3週目",
    date: "2026-04-25",
    endDate: "2026-05-01",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "春学期の授業期間（3週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-014",
    title: "春学期授業4週目",
    date: "2026-05-07",
    endDate: "2026-05-13",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "春学期の授業期間（4週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-015",
    title: "春学期授業5週目",
    date: "2026-05-14",
    endDate: "2026-05-20",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "春学期の授業期間（5週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-016",
    title: "春学期授業6週目",
    date: "2026-05-21",
    endDate: "2026-05-27",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "春学期の授業期間（6週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-017",
    title: "春学期授業7週目",
    date: "2026-05-28",
    endDate: "2026-06-03",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "春学期の授業期間（7週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-018",
    title: "春学期授業8週目",
    date: "2026-06-04",
    endDate: "2026-06-10",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "春学期の授業期間（8週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-019",
    title: "春学期授業9週目",
    date: "2026-06-11",
    endDate: "2026-06-17",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "春学期の授業期間（9週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-020",
    title: "春学期授業10週目",
    date: "2026-06-18",
    endDate: "2026-06-24",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "春学期の授業期間（10週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-021",
    title: "春学期授業11週目",
    date: "2026-06-25",
    endDate: "2026-07-01",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "春学期の授業期間（11週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-001",
    title: "春学期授業12週目",
    date: "2026-07-02",
    endDate: "2026-07-08",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "春学期の授業期間（12週目）です。",
    lastUpdated: "2026-06-25",
    isPublished: true
  },
  {
    id: "evt-002",
    title: "春学期授業13週目",
    date: "2026-07-09",
    endDate: "2026-07-15",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "春学期の授業期間（13週目）です。",
    lastUpdated: "2026-06-25",
    isPublished: true
  },
  {
    id: "evt-003",
    title: "春学期授業14週目",
    date: "2026-07-16",
    endDate: "2026-07-22",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "春学期の授業期間（14週目）です。",
    lastUpdated: "2026-06-25",
    isPublished: true
  },
  {
    id: "evt-004",
    title: "授業予備週",
    date: "2026-07-23",
    endDate: "2026-07-29",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "授業予備週の期間です。",
    lastUpdated: "2026-06-25",
    isPublished: true
  },
  {
    id: "evt-005",
    title: "夏季休業開始",
    date: "2026-07-30",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "夏季休業の開始日です。",
    lastUpdated: "2026-06-25",
    isPublished: true
  },
  {
    id: "evt-006",
    title: "オープンキャンパス",
    date: "2026-08-01",
    endDate: "2026-08-02",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    target: ["applicant", "public"],
    feeType: "free",
    feeText: "無料",
    description: "オープンキャンパス開催期間です。",
    lastUpdated: "2026-06-25",
    isPublished: true
  },
  {
    id: "evt-007",
    title: "9月卒業式",
    date: "2026-09-19",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    target: ["student", "public"],
    feeType: "free",
    feeText: "無料",
    description: "9月卒業式です。",
    lastUpdated: "2026-06-25",
    isPublished: true
  },
  {
    id: "evt-008",
    title: "夏季休業終了",
    date: "2026-09-20",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "夏季休業の終了日です。",
    lastUpdated: "2026-06-25",
    isPublished: true
  },
  {
    id: "evt-009",
    title: "9月入学式",
    date: "2026-09-26",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    target: ["student", "public"],
    feeType: "free",
    feeText: "無料",
    description: "9月入学式です。",
    lastUpdated: "2026-06-25",
    isPublished: true
  },
  {
    id: "evt-010",
    title: "秋学期授業1週目",
    date: "2026-10-01",
    endDate: "2026-10-07",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "秋学期授業1週目の期間です。",
    lastUpdated: "2026-06-25",
    isPublished: true
  },
  {
    id: "evt-022",
    title: "秋学期授業2週目",
    date: "2026-10-08",
    endDate: "2026-10-14",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "秋学期の授業期間（2週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-023",
    title: "秋学期授業3週目",
    date: "2026-10-15",
    endDate: "2026-10-21",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "秋学期の授業期間（3週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-024",
    title: "秋学期授業4週目",
    date: "2026-10-22",
    endDate: "2026-10-28",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "秋学期の授業期間（4週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-025",
    title: "秋学期授業5週目",
    date: "2026-10-29",
    endDate: "2026-11-04",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "秋学期の授業期間（5週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-026",
    title: "臨時休業",
    date: "2026-11-05",
    endDate: "2026-11-06",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "臨時休業期間です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-027",
    title: "早稲田祭",
    date: "2026-11-07",
    endDate: "2026-11-08",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "culture",
    scope: "schedule",
    target: ["student", "obog", "public"],
    feeType: "free",
    feeText: "無料",
    description: "早稲田祭の開催期間です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-028",
    title: "秋学期授業6週目",
    date: "2026-11-09",
    endDate: "2026-11-14",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "秋学期の授業期間（6週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-029",
    title: "秋学期授業7週目",
    date: "2026-11-16",
    endDate: "2026-11-21",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "秋学期の授業期間（7週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-030",
    title: "秋学期授業8週目",
    date: "2026-11-23",
    endDate: "2026-11-28",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "秋学期の授業期間（8週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-031",
    title: "秋学期授業9週目",
    date: "2026-11-30",
    endDate: "2026-12-05",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "秋学期の授業期間（9週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-032",
    title: "秋学期授業10週目",
    date: "2026-12-07",
    endDate: "2026-12-12",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "秋学期の授業期間（10週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-033",
    title: "秋学期授業11週目",
    date: "2026-12-14",
    endDate: "2026-12-19",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "秋学期の授業期間（11週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-034",
    title: "秋学期授業12週目",
    date: "2026-12-21",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "秋学期の授業期間（12週目）の一部です。冬季休業を挟んで1/6〜1/9・1/12に続きます。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-035",
    title: "冬季休業開始",
    date: "2026-12-22",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "冬季休業の開始日です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-036",
    title: "臨時休業",
    date: "2026-12-25",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "臨時休業日です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-037",
    title: "臨時休業",
    date: "2026-12-28",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "臨時休業日です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-038",
    title: "秋学期授業12週目",
    date: "2027-01-06",
    endDate: "2027-01-09",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "秋学期の授業期間（12週目）の一部です。12/21から続き、1/12にも続きます。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-039",
    title: "秋学期授業12週目",
    date: "2027-01-12",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "秋学期の授業期間（12週目）の一部です。12/21・1/6〜1/9から続きます。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-040",
    title: "秋学期授業13週目",
    date: "2027-01-13",
    endDate: "2027-01-19",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "秋学期の授業期間（13週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-041",
    title: "秋学期授業14週目",
    date: "2027-01-20",
    endDate: "2027-01-26",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "秋学期の授業期間（14週目）です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },
  {
    id: "evt-042",
    title: "授業予備期間",
    date: "2027-01-27",
    endDate: "2027-02-02",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学",
    category: "other",
    scope: "schedule",
    weeklyClassOnly: true,
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "秋学期の授業予備期間です。",
    lastUpdated: "2026-07-03",
    isPublished: true
  },

  // ========================================
  // サークル・団体イベント
  // ========================================

  {
    id: "evt-043",
    title: "第22回出版甲子園 企画応募受付期間",
    date: "2026-07-11",
    endDate: "2026-08-06",
    location: "",
    campus: "online",
    organizer: "出版甲子園実行委員会",
    category: "culture",
    scope: "circle",
    orgId: "C-003",
    target: ["student"],
    feeType: "free",
    feeText: "無料",
    description: "学生の、学生による、学生のための出版コンテスト「出版甲子園」。「本にしたい企画」を全国の学生から募集し、実行委員会の審査・ブラッシュアップを経て、決勝大会で出版業界関係者にプレゼンします。第22回大会の企画応募受付期間です（フォームより約1000字から応募可）。",
    externalUrl: "https://spk.picaso.jp/22taikai/application/",
    lastUpdated: "2026-07-10",
    isPublished: true
  },

  // ========================================
  // 早慶戦（体育各部）
  // ========================================

  {
    id: "evt-044",
    title: "早慶戦(競走部)",
    date: "2026-08-11",
    startTime: "09:00",
    location: "日吉陸上競技場",
    campus: "outside",
    organizer: "早稲田大学競走部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学競走部と慶應義塾大学による伝統の早慶戦（陸上競技）。",
    externalUrl: "https://www.waseda.jp/inst/athletic/club/track-field/",
    lastUpdated: "2026-07-29",
    isPublished: true
  },
  {
    id: "evt-045",
    title: "早慶戦(ア式蹴球部・ソッカー部) -早慶クラシコ-",
    date: "2026-08-11",
    startTime: "18:00",
    location: "MUFGスタジアム(国立競技場)",
    campus: "outside",
    organizer: "早稲田大学ア式蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "paid",
    feeText: "有料（自由席：一般2,000円/学生1,000円 ほか、S席指定3,000円）",
    description: "第77回早慶サッカー定期戦「早慶クラシコ」。早稲田大学ア式蹴球部と慶應義塾大学による伝統の一戦。",
    externalUrl: "https://www.waseda-afc.jp/news-men/145385",
    lastUpdated: "2026-07-29",
    isPublished: true
  },
  {
    id: "evt-046",
    title: "早慶戦(ウエイトリフティング部)",
    date: "2026-09-13",
    location: "慶應義塾大学日吉キャンパス日吉記念館",
    campus: "outside",
    organizer: "早稲田大学ウエイトリフティング部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学ウエイトリフティング部と慶應義塾大学による伝統の早慶戦。",
    externalUrl: "https://www.waseda.jp/inst/athletic/club/weightlifting/",
    lastUpdated: "2026-07-29",
    isPublished: true
  },
  {
    id: "evt-047",
    title: "早慶戦(剣道部 女子)",
    date: "2026-10-04",
    startTime: "12:00",
    location: "早稲田大学戸山キャンパス 早稲田アリーナ",
    campus: "toyama",
    organizer: "早稲田大学剣道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学剣道部と慶應義塾大学による伝統の早慶戦（女子）。",
    externalUrl: "http://www.waseda-kendo.com/soukei/",
    lastUpdated: "2026-07-29",
    isPublished: true
  },
  {
    id: "evt-048",
    title: "早慶戦(剣道部 男子)",
    date: "2026-10-25",
    startTime: "13:00",
    location: "早稲田大学17号館体育館2階剣道場",
    campus: "waseda",
    organizer: "早稲田大学剣道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学剣道部と慶應義塾大学による伝統の早慶戦（男子）。",
    externalUrl: "http://www.waseda-kendo.com/soukei/",
    lastUpdated: "2026-07-29",
    isPublished: true
  },
  {
    id: "evt-049",
    title: "早慶戦(ボクシング部)",
    date: "2026-12-05",
    location: "慶應義塾大学日吉キャンパス日吉記念館",
    campus: "outside",
    organizer: "早稲田大学ボクシング部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学ボクシング部と慶應義塾大学による伝統の早慶戦。",
    externalUrl: "http://www.waseda-boxing.com/",
    lastUpdated: "2026-07-29",
    isPublished: true
  },
  {
    id: "evt-050",
    title: "早慶戦(射撃部)",
    date: "2026-12-06",
    location: "伊勢原射撃場",
    campus: "outside",
    organizer: "早稲田大学射撃部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学射撃部と慶應義塾大学による伝統の早慶戦。",
    externalUrl: "https://waseda-shooting.com/",
    lastUpdated: "2026-07-29",
    isPublished: true
  },
  {
    id: "evt-051",
    title: "早慶戦(フェンシング部)",
    date: "2026-12-13",
    startTime: "09:00",
    location: "早稲田大学戸山キャンパス 早稲田アリーナ",
    campus: "toyama",
    organizer: "早稲田大学フェンシング部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学フェンシング部と慶應義塾大学による伝統の早慶戦。",
    externalUrl: "https://wasedafencing.com/",
    lastUpdated: "2026-07-29",
    isPublished: true
  },

  // ========================================
  // 体育各部 試合日程（2026年7〜12月）
  // ========================================

  // ---- 弓道部 ----
  {
    id: "evt-052",
    title: "全国大学弓道選抜大会(男子)",
    date: "2026-07-04",
    location: "明治神宮",
    campus: "outside",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学弓道部(男子)が出場する全国大学弓道選抜大会。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-053",
    title: "弓道部(男子) リーグ戦練習試合 vs青山学院大学",
    date: "2026-07-04",
    location: "早稲田大学弓道部 本道場",
    campus: "waseda",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東学生弓道リーグ戦に向けた練習試合。対 青山学院大学。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-054",
    title: "弓道部(男子) インカレ練習試合 vs明治大学",
    date: "2026-07-05",
    location: "早稲田大学弓道部 本道場",
    campus: "waseda",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "全日本学生弓道選手権大会(インカレ)に向けた練習試合。対 明治大学。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-055",
    title: "全国大学弓道選抜大会(女子)",
    date: "2026-07-05",
    location: "明治神宮",
    campus: "outside",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学弓道部(女子)が出場する全国大学弓道選抜大会。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-056",
    title: "全日本学生弓道選手権大会 個人予選(男子)",
    date: "2026-07-11",
    location: "早稲田大学弓道部 本道場",
    campus: "waseda",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "全日本学生弓道選手権大会に向けた個人予選(男子)。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-057",
    title: "弓道部(男子) リーグ戦練習試合 vs東京大学",
    date: "2026-07-12",
    location: "東京大学(本郷)",
    campus: "outside",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東学生弓道リーグ戦に向けた練習試合。対 東京大学。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-058",
    title: "全日本学生弓道選手権大会 個人予選(女子)",
    date: "2026-07-12",
    location: "早稲田大学弓道部 本道場",
    campus: "waseda",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "全日本学生弓道選手権大会に向けた個人予選(女子)。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-059",
    title: "弓道部(男子) リーグ戦練習試合 vs國學院大學",
    date: "2026-07-31",
    location: "早稲田大学弓道部 本道場",
    campus: "waseda",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東学生弓道リーグ戦に向けた練習試合。対 國學院大學。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-060",
    title: "弓道部(男子) インカレ練習試合 vs慶應義塾大学・中央大学・国際武道大学",
    date: "2026-08-05",
    location: "早稲田大学弓道部 本道場",
    campus: "waseda",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "全日本学生弓道選手権大会(インカレ)に向けた練習試合。対 慶應義塾大学・中央大学・国際武道大学。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-061",
    title: "弓道部(男子) インカレ練習試合 vs法政大学・大東文化大学",
    date: "2026-08-09",
    location: "早稲田大学弓道部 本道場",
    campus: "waseda",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "全日本学生弓道選手権大会(インカレ)に向けた練習試合。対 法政大学・大東文化大学。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-062",
    title: "弓道部(女子) インカレ練習試合 vs法政大学",
    date: "2026-08-09",
    location: "法政大学",
    campus: "outside",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "全日本学生弓道選手権大会(インカレ)に向けた練習試合。対 法政大学。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-063",
    title: "弓道部(男子) インカレ練習試合 vs明治大学",
    date: "2026-08-13",
    location: "早稲田大学弓道部 本道場",
    campus: "waseda",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "全日本学生弓道選手権大会(インカレ)に向けた練習試合。対 明治大学。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-064",
    title: "弓道部(女子) インカレ練習試合 vs中央大学",
    date: "2026-08-15",
    location: "早稲田大学弓道部 本道場",
    campus: "waseda",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "全日本学生弓道選手権大会(インカレ)に向けた練習試合。対 中央大学。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-065",
    title: "全日本学生弓道選手権大会(男女)",
    date: "2026-08-18",
    endDate: "2026-08-20",
    location: "",
    campus: "outside",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学弓道部(男女)が出場する全日本学生弓道選手権大会(インカレ)。会場は未確認。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-066",
    title: "全日本学生弓道遠的選手権大会(男女)",
    date: "2026-08-21",
    location: "",
    campus: "outside",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学弓道部(男女)が出場する全日本学生弓道遠的選手権大会。会場は未確認。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-067",
    title: "弓道部(男子) 関西大学定期戦",
    date: "2026-08-22",
    location: "関西大学",
    campus: "outside",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学弓道部(男子)と関西大学の伝統の定期戦。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-068",
    title: "弓道部(女子) 同志社大学定期戦",
    date: "2026-08-23",
    location: "同志社大学",
    campus: "outside",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学弓道部(女子)と同志社大学の伝統の定期戦。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-069",
    title: "弓道部(男子) リーグ戦練習試合 vs東京都市大学",
    date: "2026-08-23",
    location: "早稲田大学弓道部 本道場",
    campus: "waseda",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東学生弓道リーグ戦に向けた練習試合。対 東京都市大学。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-070",
    title: "弓道部(女子) リーグ戦練習試合 vs日本体育大学",
    date: "2026-08-30",
    location: "日本体育大学",
    campus: "outside",
    organizer: "早稲田大学弓道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東学生弓道リーグ戦に向けた練習試合。対 日本体育大学。",
    externalUrl: "https://www.waseda-kyudo.net/game2026/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },

  // ---- 水泳部 ----
  {
    id: "evt-071",
    title: "水球(男子) vs明治大学",
    date: "2026-08-13",
    startTime: "19:00",
    location: "千葉国際総合水泳場",
    campus: "outside",
    organizer: "早稲田大学水泳部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "第102回日本選手権水泳競技大会 水球競技。早稲田大学水泳部(水球男子) 対 明治大学。",
    externalUrl: "https://wasedaswim.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-072",
    title: "水球(女子) vs日体クラブ",
    date: "2026-08-14",
    startTime: "09:30",
    location: "千葉国際総合水泳場",
    campus: "outside",
    organizer: "早稲田大学水泳部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "第102回日本選手権水泳競技大会 水球競技。早稲田大学水泳部(水球女子) 対 日体クラブ。",
    externalUrl: "https://wasedaswim.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-073",
    title: "飛込 日本学生選手権水泳競技大会",
    date: "2026-08-29",
    endDate: "2026-08-30",
    location: "Asue大阪プール",
    campus: "outside",
    organizer: "早稲田大学水泳部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "第102回日本学生選手権水泳競技大会 飛込競技。早稲田大学水泳部(飛込)が出場。",
    externalUrl: "https://wasedaswim.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-074",
    title: "競泳 日本学生選手権水泳競技大会(横浜)",
    date: "2026-08-30",
    location: "横浜国際プール",
    campus: "outside",
    organizer: "早稲田大学水泳部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "第102回日本学生選手権水泳競技大会 競泳競技。早稲田大学水泳部(競泳)が出場。",
    externalUrl: "https://wasedaswim.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-075",
    title: "競泳 日本学生選手権水泳競技大会",
    date: "2026-09-03",
    endDate: "2026-09-06",
    location: "東和薬品RACTABドーム",
    campus: "outside",
    organizer: "早稲田大学水泳部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "第102回日本学生選手権水泳競技大会 競泳競技。早稲田大学水泳部(競泳)が出場。",
    externalUrl: "https://wasedaswim.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-076",
    title: "水球(男女) 日本学生選手権水泳競技大会",
    date: "2026-09-10",
    endDate: "2026-09-13",
    location: "千葉国際総合水泳場",
    campus: "outside",
    organizer: "早稲田大学水泳部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "第102回日本学生選手権水泳競技大会 水球競技。早稲田大学水泳部(男女)が出場。",
    externalUrl: "https://wasedaswim.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },

  // ---- 野球部 ----
  {
    id: "evt-077",
    title: "野球部 特別試合 vs東洋学園大学",
    date: "2026-07-05",
    startTime: "17:00",
    location: "ZOZOマリンスタジアム",
    campus: "outside",
    organizer: "早稲田大学野球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学野球部の特別試合。対 東洋学園大学。",
    externalUrl: "https://www.wasedabbc.org/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-078",
    title: "野球部 夏季オープン戦 vs京都大学",
    date: "2026-07-19",
    location: "",
    campus: "outside",
    organizer: "早稲田大学野球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学野球部の夏季オープン戦。対 京都大学。会場は未確認。",
    externalUrl: "https://www.wasedabbc.org/schedule/open-tournament/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-079",
    title: "野球部 オープン戦 vs東京工芸大学",
    date: "2026-07-25",
    location: "",
    campus: "outside",
    organizer: "早稲田大学野球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学野球部のオープン戦。対 東京工芸大学。会場は未確認。",
    externalUrl: "https://www.wasedabbc.org/schedule/open-tournament/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-080",
    title: "野球部 特別試合 vs高麗大学校",
    date: "2026-08-02",
    startTime: "13:30",
    location: "高麗大学校松湫野球場(韓国)",
    campus: "outside",
    organizer: "早稲田大学野球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学野球部の特別試合(海外遠征)。対 高麗大学校。",
    externalUrl: "https://www.wasedabbc.org/schedule/special/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },

  // ---- 庭球部 ----
  {
    id: "evt-081",
    title: "庭球部(男子) 全日本学生室内テニス選手権大会",
    date: "2026-08-07",
    endDate: "2026-08-22",
    location: "有明テニスの森(屋内ハード)",
    campus: "outside",
    organizer: "早稲田大学庭球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学庭球部(男子)が出場する全日本学生室内テニス選手権大会。",
    externalUrl: "https://www.wasedatennis.net/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-082",
    title: "庭球部(女子) 全日本学生室内テニス選手権大会",
    date: "2026-08-07",
    endDate: "2026-08-22",
    location: "有明テニスの森(屋内ハード)",
    campus: "outside",
    organizer: "早稲田大学庭球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学庭球部(女子)が出場する全日本学生室内テニス選手権大会。",
    externalUrl: "https://www.wasedatennis.net/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },

  // ---- 剣道部 ----
  {
    id: "evt-083",
    title: "早慶剣道部合同稽古(早慶交歓稽古)",
    date: "2026-07-21",
    startTime: "18:30",
    location: "",
    campus: "waseda",
    organizer: "早稲田大学剣道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学剣道部と慶應義塾大学剣道部の合同稽古。会場は未確認。",
    externalUrl: "http://www.waseda-kendo.com/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },

  // ---- 柔道部 ----
  {
    id: "evt-084",
    title: "柔道部 出稽古(合同練習)",
    date: "2026-07-11",
    location: "",
    campus: "outside",
    organizer: "早稲田大学柔道部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学柔道部と慶應義塾大学・東京大学・一橋大学・東京理科大学・東京科学大学による合同練習(出稽古)。会場は未確認。",
    externalUrl: "http://www.waseda-judo.com/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },

  // ---- 相撲部 ----
  {
    id: "evt-085",
    title: "全日本女子相撲岐阜大会",
    date: "2026-07-19",
    startTime: "09:30",
    location: "岐阜メモリアルセンター相撲場",
    campus: "outside",
    organizer: "早稲田大学相撲部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学相撲部(女子)が出場する全日本女子相撲岐阜大会。",
    externalUrl: "https://wasedasumo-website.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-086",
    title: "東日本学生相撲個人体重別選手権大会",
    date: "2026-07-26",
    startTime: "09:00",
    location: "靖国神社相撲場",
    campus: "outside",
    organizer: "早稲田大学相撲部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学相撲部が出場する東日本学生相撲個人体重別選手権大会。",
    externalUrl: "https://wasedasumo-website.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-087",
    title: "東日本学生相撲リーグ戦",
    date: "2026-09-19",
    startTime: "10:00",
    location: "靖国神社相撲場",
    campus: "outside",
    organizer: "早稲田大学相撲部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学相撲部が出場する東日本学生相撲リーグ戦。",
    externalUrl: "https://wasedasumo-website.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-088",
    title: "全日本女子相撲選手権大会",
    date: "2026-10-04",
    startTime: "09:30",
    location: "京都市武道センター",
    campus: "outside",
    organizer: "早稲田大学相撲部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学相撲部(女子)が出場する全日本女子相撲選手権大会。",
    externalUrl: "https://wasedasumo-website.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-089",
    title: "全国学生相撲選手権大会",
    date: "2026-10-31",
    endDate: "2026-11-01",
    startTime: "10:00",
    location: "両国国技館",
    campus: "outside",
    organizer: "早稲田大学相撲部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学相撲部が出場する全国学生相撲選手権大会。",
    externalUrl: "https://wasedasumo-website.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },

  // ---- ラグビー蹴球部 ----
  {
    id: "evt-090",
    title: "ラグビー蹴球部 練習試合 vs東京大学",
    date: "2026-07-11",
    startTime: "10:00",
    location: "東京大学 駒場キャンパス",
    campus: "outside",
    organizer: "早稲田大学ラグビー蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学ラグビー蹴球部の練習試合。対 東京大学。",
    externalUrl: "https://www.wasedarugby.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-091",
    title: "ラグビー蹴球部 関東大学対抗戦 vs日体大",
    date: "2026-09-12",
    startTime: "15:00",
    location: "駒沢オリンピック公園総合運動場陸上競技場",
    campus: "outside",
    organizer: "早稲田大学ラグビー蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東大学ラグビー対抗戦グループ。早稲田大学 対 日本体育大学。",
    externalUrl: "https://www.wasedarugby.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-092",
    title: "ラグビー蹴球部 関東大学対抗戦 vs立教大",
    date: "2026-09-27",
    startTime: "15:30",
    location: "秩父宮ラグビー場",
    campus: "outside",
    organizer: "早稲田大学ラグビー蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東大学ラグビー対抗戦グループ。早稲田大学 対 立教大学。",
    externalUrl: "https://www.wasedarugby.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-093",
    title: "ラグビー蹴球部 関東大学対抗戦 vs青山学院大",
    date: "2026-10-11",
    startTime: "13:00",
    location: "森エンジニアリング桐生スタジアム",
    campus: "outside",
    organizer: "早稲田大学ラグビー蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東大学ラグビー対抗戦グループ。早稲田大学 対 青山学院大学。",
    externalUrl: "https://www.wasedarugby.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-094",
    title: "ラグビー蹴球部 関東大学対抗戦 vs筑波大",
    date: "2026-10-25",
    startTime: "13:00",
    location: "ユアテックスタジアム仙台",
    campus: "outside",
    organizer: "早稲田大学ラグビー蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東大学ラグビー対抗戦グループ。早稲田大学 対 筑波大学。",
    externalUrl: "https://www.wasedarugby.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-095",
    title: "ラグビー蹴球部 関東大学対抗戦 vs帝京大",
    date: "2026-11-01",
    startTime: "11:30",
    location: "秩父宮ラグビー場",
    campus: "outside",
    organizer: "早稲田大学ラグビー蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東大学ラグビー対抗戦グループ。早稲田大学 対 帝京大学。",
    externalUrl: "https://www.wasedarugby.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-096",
    title: "早慶戦(ラグビー蹴球部)",
    date: "2026-11-23",
    startTime: "14:00",
    location: "秩父宮ラグビー場",
    campus: "outside",
    organizer: "早稲田大学ラグビー蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東大学ラグビー対抗戦グループ。早稲田大学 対 慶應義塾大学の伝統の早慶戦。",
    externalUrl: "https://www.wasedarugby.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-097",
    title: "早明戦(ラグビー蹴球部)",
    date: "2026-12-06",
    startTime: "14:00",
    location: "国立競技場",
    campus: "outside",
    organizer: "早稲田大学ラグビー蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東大学ラグビー対抗戦グループ。早稲田大学 対 明治大学の伝統の早明戦。",
    externalUrl: "https://www.wasedarugby.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },

  // ---- バスケットボール部 ----
  {
    id: "evt-098",
    title: "バスケ新人戦 vs仙台大学",
    date: "2026-07-07",
    startTime: "16:00",
    location: "松山市総合コミュニティセンター",
    campus: "outside",
    organizer: "早稲田大学バスケットボール部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "第4回全日本大学バスケットボール新人戦。早稲田大学 対 仙台大学。",
    externalUrl: "https://waseda-basketball.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-099",
    title: "バスケ新人戦 vs新潟医療福祉大学",
    date: "2026-07-09",
    startTime: "15:00",
    location: "松山市総合コミュニティセンター",
    campus: "outside",
    organizer: "早稲田大学バスケットボール部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "第4回全日本大学バスケットボール新人戦。早稲田大学 対 新潟医療福祉大学。",
    externalUrl: "https://waseda-basketball.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-100",
    title: "バスケ新人戦 vs東海大学九州大学",
    date: "2026-07-10",
    startTime: "17:00",
    location: "松山市総合コミュニティセンター",
    campus: "outside",
    organizer: "早稲田大学バスケットボール部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "第4回全日本大学バスケットボール新人戦。早稲田大学 対 東海大学九州大学。",
    externalUrl: "https://waseda-basketball.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-101",
    title: "バスケ新人戦 vs江戸川大学",
    date: "2026-07-11",
    startTime: "18:00",
    location: "松山市総合コミュニティセンター",
    campus: "outside",
    organizer: "早稲田大学バスケットボール部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "第4回全日本大学バスケットボール新人戦。早稲田大学 対 江戸川大学。",
    externalUrl: "https://waseda-basketball.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-102",
    title: "バスケ新人戦 3位決定戦 vs白鷗大学",
    date: "2026-07-12",
    startTime: "13:30",
    location: "松山市総合コミュニティセンター",
    campus: "outside",
    organizer: "早稲田大学バスケットボール部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "第4回全日本大学バスケットボール新人戦 3位決定戦。早稲田大学 対 白鷗大学。",
    externalUrl: "https://waseda-basketball.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-103",
    title: "第94回早関バスケットボール定期戦",
    date: "2026-07-25",
    endDate: "2026-07-26",
    location: "",
    campus: "outside",
    organizer: "早稲田大学バスケットボール部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学と関西大学の伝統の定期戦(早関戦)。時刻・会場は未確認。",
    externalUrl: "https://waseda-basketball.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },

  // ---- ア式蹴球部(サッカー) 関東大学サッカーリーグ1部 ----
  {
    id: "evt-104",
    title: "関東大学サッカーリーグ1部 第12節 vs東海大学",
    date: "2026-09-23",
    startTime: "18:00",
    location: "東海大学湘南キャンパスサッカー場",
    campus: "outside",
    organizer: "早稲田大学ア式蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "JR東日本カップ2026 第100回関東大学サッカーリーグ戦1部 第12節。早稲田大学 対 東海大学。",
    externalUrl: "https://www.waseda-afc.jp/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-105",
    title: "関東大学サッカーリーグ1部 第13節 vs国士舘大学",
    date: "2026-09-26",
    startTime: "18:00",
    location: "早稲田大学東伏見サッカー場",
    campus: "outside",
    organizer: "早稲田大学ア式蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "JR東日本カップ2026 第100回関東大学サッカーリーグ戦1部 第13節。早稲田大学 対 国士舘大学。",
    externalUrl: "https://www.waseda-afc.jp/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-106",
    title: "関東大学サッカーリーグ1部 第14節 vs東洋大学",
    date: "2026-10-03",
    startTime: "14:00",
    location: "東洋大学朝霞キャンパス・サッカー場",
    campus: "outside",
    organizer: "早稲田大学ア式蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "JR東日本カップ2026 第100回関東大学サッカーリーグ戦1部 第14節。早稲田大学 対 東洋大学。",
    externalUrl: "https://www.waseda-afc.jp/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-107",
    title: "関東大学サッカーリーグ1部 第15節 vs筑波大学",
    date: "2026-10-10",
    startTime: "14:00",
    location: "フカガワみらいフィールド",
    campus: "outside",
    organizer: "早稲田大学ア式蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "JR東日本カップ2026 第100回関東大学サッカーリーグ戦1部 第15節。早稲田大学 対 筑波大学。",
    externalUrl: "https://www.waseda-afc.jp/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-108",
    title: "関東大学サッカーリーグ1部 第16節 vs日本大学",
    date: "2026-10-17",
    startTime: "14:00",
    location: "早稲田大学東伏見サッカー場",
    campus: "outside",
    organizer: "早稲田大学ア式蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "JR東日本カップ2026 第100回関東大学サッカーリーグ戦1部 第16節。早稲田大学 対 日本大学。",
    externalUrl: "https://www.waseda-afc.jp/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-109",
    title: "関東大学サッカーリーグ1部 第17節 vs桐蔭横浜大学",
    date: "2026-10-21",
    startTime: "18:00",
    location: "早稲田大学東伏見サッカー場",
    campus: "outside",
    organizer: "早稲田大学ア式蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "JR東日本カップ2026 第100回関東大学サッカーリーグ戦1部 第17節。早稲田大学 対 桐蔭横浜大学。",
    externalUrl: "https://www.waseda-afc.jp/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-110",
    title: "関東大学サッカーリーグ1部 第18節 vs法政大学",
    date: "2026-10-24",
    startTime: "14:00",
    location: "法政大学城山サッカー場",
    campus: "outside",
    organizer: "早稲田大学ア式蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "JR東日本カップ2026 第100回関東大学サッカーリーグ戦1部 第18節。早稲田大学 対 法政大学。",
    externalUrl: "https://www.waseda-afc.jp/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-111",
    title: "関東大学サッカーリーグ1部 第19節 vs中央大学",
    date: "2026-10-31",
    startTime: "14:00",
    location: "早稲田大学東伏見サッカー場",
    campus: "outside",
    organizer: "早稲田大学ア式蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "JR東日本カップ2026 第100回関東大学サッカーリーグ戦1部 第19節。早稲田大学 対 中央大学。",
    externalUrl: "https://www.waseda-afc.jp/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-112",
    title: "関東大学サッカーリーグ1部 第20節 vs駒澤大学",
    date: "2026-11-03",
    startTime: "14:00",
    location: "早稲田大学東伏見サッカー場",
    campus: "outside",
    organizer: "早稲田大学ア式蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "JR東日本カップ2026 第100回関東大学サッカーリーグ戦1部 第20節。早稲田大学 対 駒澤大学。",
    externalUrl: "https://www.waseda-afc.jp/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-113",
    title: "関東大学サッカーリーグ1部 第21節 vs明治大学",
    date: "2026-11-07",
    startTime: "14:00",
    location: "神奈川県立保土ケ谷公園サッカー場",
    campus: "outside",
    organizer: "早稲田大学ア式蹴球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "JR東日本カップ2026 第100回関東大学サッカーリーグ戦1部 第21節。早稲田大学 対 明治大学。",
    externalUrl: "https://www.waseda-afc.jp/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },

  // ---- 空手部 ----
  {
    id: "evt-114",
    title: "早慶戦(空手部) 第84回早慶空手定期戦",
    date: "2026-12-07",
    location: "早稲田アリーナ",
    campus: "toyama",
    organizer: "早稲田大学空手部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学空手部と慶應義塾大学による第84回早慶空手定期戦。",
    externalUrl: "https://www.waseda-karatebu.org/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },

  // ---- ラクロス部(男子・RED BATS) ----
  {
    id: "evt-115",
    title: "ラクロス部(男子) 関東学生リーグ戦 vs成蹊大学",
    date: "2026-08-22",
    startTime: "16:00",
    location: "大井ホッケー場 メイン",
    campus: "outside",
    organizer: "早稲田大学ラクロス部(男子)",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "2026関東学生リーグ戦Aブロック。早稲田大学 対 成蹊大学。",
    externalUrl: "http://wlax-redbats.com/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-116",
    title: "ラクロス部(男子) 関東学生リーグ戦 vs中央大学",
    date: "2026-09-05",
    startTime: "18:20",
    location: "大井ホッケー場 メイン",
    campus: "outside",
    organizer: "早稲田大学ラクロス部(男子)",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "2026関東学生リーグ戦Aブロック。早稲田大学 対 中央大学。",
    externalUrl: "http://wlax-redbats.com/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-117",
    title: "ラクロス部(男子) 関東学生リーグ戦 vs慶應義塾大学",
    date: "2026-09-13",
    startTime: "09:00",
    location: "大井ホッケー場 サブ",
    campus: "outside",
    organizer: "早稲田大学ラクロス部(男子)",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "2026関東学生リーグ戦Aブロック。早稲田大学 対 慶應義塾大学。",
    externalUrl: "http://wlax-redbats.com/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-118",
    title: "ラクロス部(男子) 関東学生リーグ戦 vs明治大学",
    date: "2026-09-27",
    startTime: "09:00",
    location: "大井ホッケー場 メイン",
    campus: "outside",
    organizer: "早稲田大学ラクロス部(男子)",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "2026関東学生リーグ戦Aブロック。早稲田大学 対 明治大学。",
    externalUrl: "http://wlax-redbats.com/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },

  // ---- ラクロス部(女子) ----
  {
    id: "evt-119",
    title: "ラクロス部(女子) リーグ戦2026 vs立教大学",
    date: "2026-07-04",
    location: "富士通スタジアム",
    campus: "outside",
    organizer: "早稲田大学ラクロス部(女子)",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東学生女子ラクロスリーグ戦2026。早稲田大学 対 立教大学。",
    externalUrl: "http://w-lax.com/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-120",
    title: "ラクロス部(女子) 準リーグ vs立教大学γ",
    date: "2026-07-11",
    location: "",
    campus: "outside",
    organizer: "早稲田大学ラクロス部(女子)",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東学生女子ラクロス準リーグ。早稲田大学 対 立教大学γ。会場は未確認。",
    externalUrl: "http://w-lax.com/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-121",
    title: "ラクロス部(女子) Vリーグ vs東海大学",
    date: "2026-07-25",
    location: "",
    campus: "outside",
    organizer: "早稲田大学ラクロス部(女子)",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東学生女子ラクロスVリーグ。早稲田大学 対 東海大学。会場は未確認。",
    externalUrl: "http://w-lax.com/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-122",
    title: "ラクロス部(女子) Vリーグ vs学習院大学",
    date: "2026-07-26",
    location: "",
    campus: "outside",
    organizer: "早稲田大学ラクロス部(女子)",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東学生女子ラクロスVリーグ。早稲田大学 対 学習院大学。会場は未確認。",
    externalUrl: "http://w-lax.com/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-123",
    title: "ラクロス部(女子) 準リーグ vs法政大学",
    date: "2026-08-01",
    location: "",
    campus: "outside",
    organizer: "早稲田大学ラクロス部(女子)",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東学生女子ラクロス準リーグ。早稲田大学 対 法政大学。会場は未確認。",
    externalUrl: "http://w-lax.com/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-124",
    title: "ラクロス部(女子) Vリーグ vs日本大学",
    date: "2026-08-05",
    location: "",
    campus: "outside",
    organizer: "早稲田大学ラクロス部(女子)",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東学生女子ラクロスVリーグ。早稲田大学 対 日本大学(公式サイト表記「日大中高」、要確認)。会場は未確認。",
    externalUrl: "http://w-lax.com/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-125",
    title: "ラクロス部(女子) リーグ戦2026 vs東京大学",
    date: "2026-08-08",
    location: "",
    campus: "outside",
    organizer: "早稲田大学ラクロス部(女子)",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東学生女子ラクロスリーグ戦2026。早稲田大学 対 東京大学。会場は未確認。",
    externalUrl: "http://w-lax.com/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-126",
    title: "ラクロス部(女子) 準リーグ vs慶應義塾大学",
    date: "2026-08-16",
    location: "",
    campus: "outside",
    organizer: "早稲田大学ラクロス部(女子)",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東学生女子ラクロス準リーグ。早稲田大学 対 慶應義塾大学。会場は未確認。",
    externalUrl: "http://w-lax.com/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-127",
    title: "ラクロス部(女子) リーグ戦2026 vs慶應義塾大学",
    date: "2026-08-23",
    location: "",
    campus: "outside",
    organizer: "早稲田大学ラクロス部(女子)",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "関東学生女子ラクロスリーグ戦2026。早稲田大学 対 慶應義塾大学。会場は未確認。",
    externalUrl: "http://w-lax.com/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },

  // ---- 少林寺拳法部 ----
  {
    id: "evt-128",
    title: "少林寺拳法部 東京都大会立合二次予選",
    date: "2026-07-05",
    location: "立教大学新座キャンパス",
    campus: "outside",
    organizer: "早稲田大学少林寺拳法部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学少林寺拳法部が出場する東京都大会 立合二次予選。",
    externalUrl: "http://waseda-shorinji.com/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },

  // ---- 自動車部 ----
  {
    id: "evt-129",
    title: "全日本学生ダートトライアル選手権大会",
    date: "2026-08-08",
    endDate: "2026-08-09",
    location: "モーターランド野沢",
    campus: "outside",
    organizer: "早稲田大学自動車部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学自動車部が出場する全日本学生ダートトライアル選手権大会。",
    externalUrl: "http://wuac.com/posts/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-130",
    title: "全日本学生ジムカーナ選手権大会",
    date: "2026-08-30",
    location: "鈴鹿サーキット国際南コース",
    campus: "outside",
    organizer: "早稲田大学自動車部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学自動車部が出場する全日本学生ジムカーナ選手権大会。連盟公式発表では8/29〜30の可能性あり(要確認)。",
    externalUrl: "http://wuac.com/posts/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-131",
    title: "全日本学生自動車運転競技選手権大会(10月)",
    date: "2026-10-26",
    location: "鈴鹿サーキット",
    campus: "outside",
    organizer: "早稲田大学自動車部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学自動車部が出場する全日本学生自動車運転競技選手権大会。全日本学生自動車連盟の公式発表とは日程が異なり(要確認)。",
    externalUrl: "http://wuac.com/posts/schedule/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-132",
    title: "全日本学生自動車運転競技選手権大会(11月)",
    date: "2026-11-03",
    location: "鈴鹿サーキット",
    campus: "outside",
    organizer: "早稲田大学自動車部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "全日本学生自動車連盟公式発表による全日本学生自動車運転競技選手権大会(11/3・鈴鹿サーキット)。早稲田大学自動車部サイトの10/26表記との整合は未確認。",
    externalUrl: "https://www.ajsaa-alljapan.org/blank-2",
    lastUpdated: "2026-07-30",
    isPublished: true
  },

  // ---- 準硬式野球部 ----
  {
    id: "evt-133",
    title: "準硬式野球部 OP戦 vs東北学院大学・国士館大学",
    date: "2026-07-11",
    location: "早稲田大学東伏見キャンパス軟式野球場",
    campus: "outside",
    organizer: "早稲田大学準硬式野球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学準硬式野球部のオープン戦(変則ダブルヘッダー)。対 東北学院大学・国士館大学。",
    externalUrl: "https://w-junkoh.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-134",
    title: "準硬式野球部 OP戦 vs国士館大学世田谷",
    date: "2026-07-12",
    location: "早稲田大学東伏見キャンパス軟式野球場",
    campus: "outside",
    organizer: "早稲田大学準硬式野球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学準硬式野球部のオープン戦(ダブルヘッダー)。対 国士館大学世田谷。",
    externalUrl: "https://w-junkoh.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-135",
    title: "準硬式野球部 OP戦 vs帝京大学",
    date: "2026-07-28",
    location: "早稲田大学東伏見キャンパス軟式野球場",
    campus: "outside",
    organizer: "早稲田大学準硬式野球部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学準硬式野球部のオープン戦(ダブルヘッダー)。対 帝京大学。",
    externalUrl: "https://w-junkoh.com/schedule",
    lastUpdated: "2026-07-30",
    isPublished: true
  },

  // ---- バドミントン部 ----
  {
    id: "evt-136",
    title: "第69回東日本学生バドミントン選手権大会",
    date: "2026-08-26",
    endDate: "2026-09-04",
    location: "",
    campus: "outside",
    organizer: "早稲田大学バドミントン部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学バドミントン部(男女)が出場する第69回東日本学生バドミントン選手権大会。開催地は北海道。",
    externalUrl: "https://waseda-bad.com/blog/%E5%B9%B4%E9%96%93%E3%82%B9%E3%82%B1%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-137",
    title: "第77回全日本学生バドミントン選手権大会",
    date: "2026-10-16",
    endDate: "2026-10-22",
    location: "",
    campus: "outside",
    organizer: "早稲田大学バドミントン部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学バドミントン部(男女)が出場する第77回全日本学生バドミントン選手権大会。開催地は石川県。",
    externalUrl: "https://waseda-bad.com/blog/%E5%B9%B4%E9%96%93%E3%82%B9%E3%82%B1%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-138",
    title: "第77回全日本学生バドミントン大学対抗戦",
    date: "2026-11-05",
    endDate: "2026-11-08",
    location: "",
    campus: "outside",
    organizer: "早稲田大学バドミントン部",
    category: "sports",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学バドミントン部(男女)が出場する第77回全日本学生バドミントン大学対抗戦。開催地は兵庫県。",
    externalUrl: "https://waseda-bad.com/blog/%E5%B9%B4%E9%96%93%E3%82%B9%E3%82%B1%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },

  // ---- 応援部 ----
  {
    id: "evt-139",
    title: "第77回早慶サッカー定期戦壮行会",
    date: "2026-07-01",
    location: "3号館前",
    campus: "waseda",
    organizer: "早稲田大学応援部",
    category: "culture",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "free",
    feeText: "無料",
    description: "早慶クラシコ(第77回早慶サッカー定期戦)に向けた応援部主催の壮行会。お昼休みに開催。",
    externalUrl: "http://www.w-ouen.com/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-140",
    title: "東京六大学応援団連盟 第50回合同演奏会",
    date: "2026-07-11",
    startTime: "18:00",
    location: "府中の森芸術劇場",
    campus: "outside",
    organizer: "早稲田大学応援部",
    category: "culture",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "東京六大学応援団連盟 吹奏楽部・チアリーディング部による第50回合同演奏会。開場17:30。",
    externalUrl: "http://www.w-ouen.com/",
    lastUpdated: "2026-07-30",
    isPublished: true
  },
  {
    id: "evt-141",
    title: "北風祭2026",
    date: "2026-07-12",
    startTime: "11:00",
    location: "早稲田大学ラグビー場(会場表記に「上井草グラウンド」との情報もあり要確認)",
    campus: "outside",
    organizer: "早稲田大学応援部",
    category: "culture",
    scope: "circle",
    target: ["student", "obog", "public"],
    feeType: "unknown",
    feeText: "料金不明",
    description: "早稲田大学応援部の伝統行事「北風祭」。開祭式11:00、応援部ステージ11:20〜。",
    externalUrl: "http://www.w-ouen.com/",
    lastUpdated: "2026-07-30",
    isPublished: true
  }

];

/**
 * カテゴリの日本語ラベル定義
 */
const CATEGORY_LABELS = {
  sports:    "スポーツ",
  culture:   "文化",
  music:     "音楽",
  theater:   "演劇",
  lecture:   "講演",
  community: "地域",
  other:     "その他"
};

/**
 * 大枠フィルタ（scope）の日本語ラベル定義
 */
const SCOPE_LABELS = {
  schedule: "学事日程",
  circle:   "サークルイベント"
};

/**
 * 対象者の日本語ラベル定義
 */
const TARGET_LABELS = {
  student:   "在学生向け",
  obog:      "OBOG向け",
  public:    "一般参加可",
  applicant: "受験生向け"
};

/**
 * キャンパス・場所の日本語ラベル定義
 */
const CAMPUS_LABELS = {
  waseda:       "早稲田キャンパス",
  toyama:       "戸山キャンパス",
  nishiwaseda:  "西早稲田キャンパス",
  tokorozawa:   "所沢キャンパス",
  takadanobaba: "高田馬場周辺",
  outside:      "学外",
  online:       "オンライン"
};

/**
 * 参加費種別の日本語ラベル定義
 */
const FEE_LABELS = {
  free: "無料",
  paid: "有料",
  unknown: "料金不明"
};
